---

- name: setup packages 
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ debian_packages }}"

- name: link pip3 to pip
  file:
    src: /usr/bin/pip3
    dest: /usr/local/bin/pip
    state: link

- name: create apps directories
  file:
    path: "{{ item.value.app_path }}"
    owner: "{{ item.value.app_uid }}"
    group: "{{ item.value.app_gid }}"
    mode: "{{ item.value.app_dir_mode }}"
    state: "{{ item.value.state }}"
  with_dict: "{{ app_dirs }}"

- name: create .docker directory
  file:
    path: "/home/{{ item }}/.docker"
    owner: "{{ item }}"
    group: docker
    mode: 0700
    state: directory
  with_items:
    - jmirre
    - kraken

- name: setup mounts
  mount:
    path: "{{ item.value.path }}"
    src: "{{ item.value.src }}"
    fstype: "{{ item.value.fstype }}"
    opts: "{{ item.value.opts }}"
    state: "{{ item.value.state }}"
  with_dict: "{{ mounts }}"



- debug:
    msg: "Registry host: {{registry_host}}\nUsername: {{ registry_username }}\nPass: {{ registry_password }}\n."

- name: setup config.json template
  template:
    src: ../templates/config.json.j2
    dest: "/home/{{ item }}/.docker/config.json"
  with_items:
    - kraken
    - jmirre
  #- name: setup docker login to proxy registry # TODO Setup dict with nexus REPO
  #  docker_login:
  #    registry: "{{ registry_host }}"
  #    username: "{{ registry_username }}"
  #    password: "{{ registry_password }}"
  #  #  email: "{{ registry_email }}"
  #    state: "{{ registry_state }}"
