---
- name: add users
  user:
    name: "{{ item.key }}"
    groups: "{{ item.value.groups }}"
  with_dict: "{{ users }}"

- name: setup key files
  authorized_key:
    user: "{{ item.key }}"
    state: present
    key: "{{ item.value.key}}"
  with_dict: "{{ users }}"

- name: bootstrap sudoers
  lineinfile: 
    path: /etc/sudoers
    state: present
    regexp: '^%wheel\s'
    line: '%wheel ALL=(ALL) ALL' 
- name: setup special users
  lineinfile:
    create: yes
    path: "/etc/sudoers.d/{{ item.key }}"
    state: present
    regexp: "{{ item.key }}.*"
  #  line: "{{ item.key }} ALL=(ALL) NOPASSWD: ALL"
    line: "{{ item.value.permissions }}"
  with_dict: "{{ users }}"
  when: item.value.permissions is defined
