#!/bin/bash
git checkout --orphan latest_branch

git add -A

git commit -am "commit message"

git branch -D master

git branch -m master

git push -f origin master
git rm -r --cached .

git add .

git commit -m "fixed untracked files"
