---
  - hosts: "{{ target }}"
    gather_facts: false
    become: True
    vars_files:
      - vars/vars.yml
    pre_tasks:
      - setup:
        filter: ansible_*
    tasks:

  #    - name: get related variables
  #      debug:
  #        var: "{{hostvars[ansible_system]}}"
  #      register: os

      - name: Distribution related tasks
        include_tasks: "tasks/{{ansible_os_family}}.yml"
  #   - name: shell ls
  #     command: ls
  #     register: output
  # - debug:
  #       var: output

  #   - name: update packages
  #     yum:
  #       name: '*'
  #       state: latest
  #     when: ansible_os_family == 'RedHat'
  #   - name: install required packages
  #     yum:
  #       name: "{{ item }}"
  #       state: latest
  #     with_items:
  #     - "{{ yum_packages }}"
  #     when: ansible_os_family == 'RedHat'


    #  - include: ../bootstrap.yml
