---
  - hosts: "{{ target }}"
    gather_facts: false
    become: True
    connection: local
    vars_files:

      - ../defaults/backup.yml
    pre_tasks:
      - setup:
        filter: ansible_*
    tasks:
  #    - name: get related variables
  #      debug:
  #        var: "{{hostvars[ansible_system]}}"
  #      register: os

      - name: Distribution related tasks
        include_tasks: "{{ansible_distribution}}.yml"

    #  - include: ../bootstrap.yml
