---
packages: ['wget', 'docker-ce', 'git', 'net-tools', 'bind-utils', 'iptables-services', 'bridge-utils', 'bash-completion', 'epel-release', 'sudo', 'vim', 'libselinux-python', 'yum-utils', 'device-mapper-persistent-data', 'lvm2' ]
selinux_state: enforcing
selinux_policy: targeted
DOCKER_GPG_KEY: '060A 61C5 1B55 8A7F 742B 77AA C52F EB6B 621E 9F35'
DOCKER_REPO_URL:  'https://download.docker.com/linux/centos/docker-ce.repo'
docker_vg: docker
conf_files: ['etc/lvm/profile/docker-thinpool.profile', 'etc/docker/daemon.json' ]
docker_dir: /var/lib/docker
#pvs_disk: /dev/vdb
pvs_disk: /dev/md127
docker_volumes:
  - name: thinpool
    size: 95%VG
    opts: --wipesignatures y
    path: "/dev/{{docker_vg}}/thinpool"

  - name: thinpoolmeta
    size: 1%VG
    opts: --wipesignatures y
    path: "/dev/{{docker_vg}}/thinpoolmeta"
