author: jonnenauha
exporter_file: prometheus_varnish_exporter
exporter_version: 1.3.3
exporter_port: 9131
exporter_url: https://github.com/{{author}}/{{exporter_file}}/releases/download/{{exporter_version}}/{{exporter_file}}-{{exporter_version}}.{{ansible_system|lower}}-amd64.tar.gz
exporter_args: ""

pkgs_freebsd: ['node_exporter', 'gtar', 'git', 'vim-lite']
pkgs_linux: ['prometheus-node-exporter', 'vim']
scrape: 5s
evaluation: 5s
prometheus_hosts:
prometheus_server: prometheus-preprod
directories:
  optional:
    path: '/opt'
    user: 'root'
    group: 'wheel'
    mode: '0755'
    recurse: True
    state: directory
  exporter:
    path: "/opt/{{exporter_file}}"
    user: 'root'
    group: 'wheel'
    mode: '755'
    recurse: True
    state: directory
