---
  - hosts: "{{ target }}"
    gather_facts: false
    become: True
    pre_tasks:
      - setup:
        filter: ansible_*
    tasks:
      - name: Distribution related tasks
        include_tasks: "{{ansible_os_family}}.yml"

    #  - include: ../bootstrap.yml
